apiVersion: v1
kind: Service
metadata:
  name: {{ include "nursing-sas-ope-info.fullname" . }}
  labels:
    {{- include "nursing-sas-ope-info.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "nursing-sas-ope-info.selectorLabels" . | nindent 4 }}
